
const CRED_SOURCES = { ME: 'me', TRUSTED: 'trusted', FOLLOWED: 'followed',
 SPECIFIED: 'specified'};
const VALIDITY_TYPES = { CONFIRMED: 'confirmed', REFUTED: 'refuted',
  DEBATED: 'debated', QUESTIONED: 'questioned', ALL: 'all' };
const SEEN_STATUS = { 'SEEN': 'seen', 'NOTSEEN': 'not seen' };
const VALIDITY_CODES = { 'CONFIRMED': 1, 'REFUTED': -1, 'QUESTIONED': 0 };

const ASSESSMENT_DECAY_FACTOR = 0.7;
const ASSESSMENT_UPDATE_THRESHOLD = 0.05;
const ASSESSMENT_ZERO_THRESHOLD = 0.1;

const TOKEN_TYPES = {'ACOUNT_VERIFICATION': 1, 'ACOUNT_RECOVERY': 2, 'OUTSIDE_SOURCE_ASSESSMENT': 3}
const TOKEN_EXP = {'ACCOUNT_VERIFICATION': 6 * 3600 * 1000, 'ACOUNT_RECOVERY': 4 * 3600 * 1000}; //in ms
const CLIENT_BASE_URL='http://localhost:8080';
//const CLIENT_BASE_URL='http://trustnet.csail.mit.edu';
const SITE_NAME = 'Trustnet'
const LENGTH_TO_HASH = 25;

module.exports = {
  CRED_SOURCES,
  VALIDITY_TYPES,
  SEEN_STATUS,
  VALIDITY_CODES,
  ASSESSMENT_DECAY_FACTOR,
  ASSESSMENT_UPDATE_THRESHOLD,
  ASSESSMENT_ZERO_THRESHOLD,
  TOKEN_TYPES,
  TOKEN_EXP,
  CLIENT_BASE_URL,
  SITE_NAME,
  LENGTH_TO_HASH
}
