
const CRED_SOURCES = {'ME': 'me', 'TRUSTED': 'trusted', 'USERNAMES': 'usernames'};
const VALIDITY_TYPES = {'CONFIRMED': 'confirmed', 'REFUTED': 'refuted',
  'DEBATED': 'debated', 'QUESTIONED': 'questioned'};
const SEEN_STATUS = {'SEEN': 'seen', 'NOTSEEN': 'not seen'};
const VALIDITY_CODES = {'CONFIRMED': 1, 'REFUTED': -1, 'QUESTIONED': 0};
const ASSESSMENT_DECAY_FACTOR = 0.7;
const ASSESSMENT_UPDATE_THRESHOLD = 0.05;
const ASSESSMENT_ZERO_THRESHOLD = 0.1;

module.exports = {
  CRED_SOURCES,
  VALIDITY_TYPES,
  SEEN_STATUS,
  VALIDITY_CODES,
  ASSESSMENT_DECAY_FACTOR,
  ASSESSMENT_UPDATE_THRESHOLD,
  ASSESSMENT_ZERO_THRESHOLD
}
